In [1]:
import pandas as pd

In [5]:
df1=pd.read_csv(r"C:\Users\ANAMIKA\Downloads\Titanic-Dataset.csv")
df1

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [6]:
df1.ndim

2

In [8]:
df1.shape

(891, 12)

In [10]:
df1.size

10692

In [12]:
df1.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [14]:
df1.head(8)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S

In [16]:
df1.tail(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [17]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [19]:
df1.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [20]:
df1.describe(include='object')

                       Name   Sex  Ticket Cabin Embarked
count                   891   891     891   204      889
unique                  891     2     681   147        3
top     Dooley, Mr. Patrick  male  347082    G6        S
freq                      1   577       7     4      644

In [21]:
df1[['PassengerId','Name','Age','Sex','Survived']]

,PassengerId,Name,Age,Sex,Survived
0,1,"Braund, Mr. Owen Harris",22.0,male,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,female,1
2,3,"Heikkinen, Miss. Laina",26.0,female,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,female,1
4,5,"Allen, Mr. William Henry",35.0,male,0
...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",27.0,male,0
887,888,"Graham, Miss. Margaret Edith",19.0,female,1
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",NaN,female,0
889,890,"Behr, Mr. Karl Howell",26.0,male,1
890,891,"Dooley, Mr. Patrick",32.0,male,0

In [22]:
df1.loc[9]

PassengerId                                     10
Survived                                         1
Pclass                                           2
Name           Nasser, Mrs. Nicholas (Adele Achem)
Sex                                         female
Age                                           14.0
SibSp                                            1
Parch                                            0
Ticket                                      237736
Fare                                       30.0708
Cabin                                          NaN
Embarked                                         C
Name: 9, dtype: object

In [24]:
df1.loc[4:14]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S

In [26]:
df1.loc[19:29,['Name','Fare']]

                                                 Name      Fare
19                            Masselmani, Mrs. Fatima    7.2250
20                               Fynney, Mr. Joseph J   26.0000
21                              Beesley, Mr. Lawrence   13.0000
22                        McGowan, Miss. Anna "Annie"    8.0292
23                       Sloper, Mr. William Thompson   35.5000
24                      Palsson, Miss. Torborg Danira   21.0750
25  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...   31.3875
26                            Emir, Mr. Farred Chehab    7.2250
27                     Fortune, Mr. Charles Alexander  263.0000
28                      O'Dwyer, Miss. Ellen "Nellie"    7.8792
29                                Todoroff, Mr. Lalio    7.8958

In [27]:
df1.iloc[:10]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [28]:
df1.iloc[-5:]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [29]:
df1.iloc[2:12,1:5]

,Survived,Pclass,Name,Sex
2,1,3,"Heikkinen, Miss. Laina",female
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female
4,0,3,"Allen, Mr. William Henry",male
5,0,3,"Moran, Mr. James",male
6,0,1,"McCarthy, Mr. Timothy J",male
7,0,3,"Palsson, Master. Gosta Leonard",male
8,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female
9,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female
10,1,3,"Sandstrom, Miss. Marguerite Rut",female
11,1,1,"Bonnell, Miss. Elizabeth",female

In [32]:
df1["Ticket_Fare_Category"]="Medium"
df1.loc[df1["Fare"]<20,"Ticket_Fare_Category"]="Low"
df1.loc[df1["Fare"]>50,"Ticket_Fare_Category"]="High"
print(df1)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked Ticket_Fare_Category
0        0         A/5 21171   7.2500   NaN        S                  Low
1        0          PC 17599  71.2833   C85        C                 High
2        0  STON/O2. 3101282   7.9250   NaN        S                  Low
3        0            113803  53.1000  C123        S                 High
4        0            373450   8.0500   NaN        S                  Low
..     ...               ...      ...   ...      ...                  ...
886      0            211536  13.0000   NaN        S                  Low
887      0            112053  30.0000   B42        S               Medium
888      2        W./C. 6607  23.4500   NaN        S               Medium
889      0            111369  30.0000  C148        C               Medium
890      0            370376   7.7500   NaN        Q                  Low

[891 rows x 13 columns]

In [34]:
df1.loc[df1["PassengerId"]==25,"Cabin"]="B101"
df1

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Ticket_Fare_Category
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Low
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,High
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Low
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,High
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,Low
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Medium
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,Medium
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Medium
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,Low

In [36]:
df=df1.drop(["Ticket","Cabin"],axis=1)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Embarked,Ticket_Fare_Category
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,7.2500,S,Low
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,71.2833,C,High
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,7.9250,S,Low
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,53.1000,S,High
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,8.0500,S,Low
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,13.0000,S,Low
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,30.0000,S,Medium
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,23.4500,S,Medium
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,30.0000,C,Medium
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,7.7500,Q,Low

In [37]:
df.drop([5,10,15])

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Embarked,Ticket_Fare_Category
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,7.2500,S,Low
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,71.2833,C,High
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,7.9250,S,Low
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,53.1000,S,High
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,8.0500,S,Low
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,13.0000,S,Low
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,30.0000,S,Medium
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,23.4500,S,Medium
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,30.0000,C,Medium
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,7.7500,Q,Low

In [38]:
df['Survived']==1

0      False
1       True
2       True
3       True
4      False
       ...
886    False
887     True
888    False
889     True
890    False
Name: Survived, Length: 891, dtype: bool

In [39]:
df['Survived']==0

0       True
1      False
2      False
3      False
4       True
       ...
886     True
887    False
888     True
889    False
890     True
Name: Survived, Length: 891, dtype: bool

In [47]:
df['Age']>30

0      False
1       True
2      False
3       True
4       True
       ...
886    False
887    False
888    False
889    False
890     True
Name: Age, Length: 891, dtype: bool

In [41]:
df['Fare']>100

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: Fare, Length: 891, dtype: bool

In [42]:
df.sort_values('Name',ascending=False)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Embarked,Ticket_Fare_Category
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,9.5000,S,Low
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,14.5000,S,Low
361,362,0,2,"del Carlo, Mr. Sebastiano",male,29.0,1,0,27.7208,C,Medium
282,283,0,3,"de Pelsmaeker, Mr. Alfons",male,16.0,0,0,9.5000,S,Low
286,287,1,3,"de Mulder, Mr. Theodore",male,30.0,0,0,9.5000,S,Low
...,...,...,...,...,...,...,...,...,...,...,...
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,24.0000,C,Medium
308,309,0,2,"Abelson, Mr. Samuel",male,30.0,1,0,24.0000,C,Medium
279,280,1,3,"Abbott, Mrs. Stanton (Rosa Hunt)",female,35.0,1,1,20.2500,S,Medium
746,747,0,3,"Abbott, Mr. Rossmore Edward",male,16.0,1,1,20.2500,S,Medium
845,846,0,3,"Abbing, Mr. Anthony",male,42.0,0,0,7.5500,S,Low

In [43]:
df.sort_values('Age')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Embarked,Ticket_Fare_Category
803,804,1,3,"Thomas, Master. Assad Alexander",male,0.42,0,1,8.5167,C,Low
755,756,1,2,"Hamalainen, Master. Viljo",male,0.67,1,1,14.5000,S,Low
644,645,1,3,"Baclini, Miss. Eugenie",female,0.75,2,1,19.2583,C,Low
469,470,1,3,"Baclini, Miss. Helene Barbara",female,0.75,2,1,19.2583,C,Low
78,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,29.0000,S,Medium
...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,7.2292,C,Low
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,69.5500,S,High
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,9.5000,S,Low
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,7.8958,S,Low
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,23.4500,S,Medium

In [44]:
df['Age']==df['Age'].max()

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: Age, Length: 891, dtype: bool

In [45]:
df['Age']==df['Age'].min()

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: Age, Length: 891, dtype: bool

In [46]:
df["Fare"]==df['Fare'].max()

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: Fare, Length: 891, dtype: bool